#BITWISE OPERATORS

#BITWISE AND(&)- WE USE THIS SYMBOL AS 'AND' IN BITWISE OPERATORS)BITWISE OPERATOR
a = 12
b = 13
print(a&b)

x = 25
y = 35
print(x&y)

#BITWISE OR(|) - WE USE THIS SYMBOL AS 'OR' IN BITWISE OPERATORS)BITWISE OPERATOR
p = 45
q = 35
print(p|q) #(we already written in notes that how it works)

#BITWISE XOR(^) - WE USE THIS SYMBOL AS 'XOR' IN BITWISE OPERATORS)BITWISE OPERATOR
a = 21
b = 25
print(a^b)

#BITWISE NOT(~) - WE USE THIS SYMBOL AS 'NOT' IN BITWISE OPERATORS)BITWISE OPERATOR
a = 12 #(we have written the notes for this)
print(~a)


#BITWISE LEFT SHIFT(<<) - WE USE THIS SYMBOL AS 'BITWISE LEFT' IN BITWISE OPERATORS
a = 2
print(a<<2) #WE HAVE WRITTEN THE NOTES FOR THIS


#BITWISE RIGHT SHIFT(>>) - WE USE THIS SYMBOL AS 'BITWISE RIGHT' IN BITWISE OPERATORS
a = 2
print(a>>1) #WE HAVE WRITTEN THE NOTES FOR THIS